// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruvqyfrcvjfztordeqpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1dnF5ZnJjdmpmenRvcmRlcXBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTkwNDUsImV4cCI6MjA3MTc5NTA0NX0.krKwojSLk-Otg3l5K9PHCmkVhboUxLIYDXXWOc9nCEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});